
const esc = s => String(s ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const byId=id=>document.getElementById(id);
const LEVELS=['ALL','A1','A2','B1','B2'];
let passages=[],notesObj={},exercises=[],flashcards=[],conjugations=[],sentences=[],vocabItems=[];
let exPool=[],exIndex=0,exCurrent=null,fcPool=[],fcIndex=0,fcFlipped=false,sentPool=[],sentIndex=0,sentCurrent=null,typingStarted=false,typingStartMs=0,matchPool=[],matchSelected=[],matchSolved=0,matchLastWord='',verbQuiz=null;
function normAnswer(s){return String(s??'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[„“”"'`´.,!?;:()\-]/g,' ').replace(/\s+/g,' ').trim()}
function setStatus(t){byId('status').textContent=t}
function loadJson(name){return fetch(name).then(r=>{if(!r.ok) throw new Error(name); return r.json()})}
function shuffle(a){const x=a.slice(); for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)); [x[i],x[j]]=[x[j],x[i]]} return x}
function makeId(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function todayKey(){return new Date().toISOString().slice(0,10)}
function getTodayProgress(){const all=JSON.parse(localStorage.getItem('daily_progress')||'{}'); return all[todayKey()]||{typing:0,exercises:0,sentences:0,vocab:0}}
function setTodayProgress(obj){const all=JSON.parse(localStorage.getItem('daily_progress')||'{}'); all[todayKey()]=obj; localStorage.setItem('daily_progress',JSON.stringify(all)); renderMissionBars(); renderDashboard()}
function addTodayProgress(patch){const cur=getTodayProgress(); Object.keys(patch).forEach(k=>cur[k]=(cur[k]||0)+(patch[k]||0)); setTodayProgress(cur)}
function getMission(){return JSON.parse(localStorage.getItem('daily_mission')||'null')||{preset:'medium',level:'All',typing:3,exercises:10,sentences:5,vocab:10}}
function setMission(m){localStorage.setItem('daily_mission',JSON.stringify(m)); renderMissionBars(); renderDashboard()}
function applyMissionPreset(){const preset=byId('missionPreset').value, level=byId('missionLevel').value; let m={preset,level}; if(preset==='easy') Object.assign(m,{typing:1,exercises:10,sentences:5,vocab:10}); else if(preset==='medium') Object.assign(m,{typing:3,exercises:20,sentences:10,vocab:20}); else if(preset==='hard') Object.assign(m,{typing:5,exercises:40,sentences:20,vocab:40}); else Object.assign(m,getMission(),{preset,level}); setMission(m)}
function resetTodayProgress(){setTodayProgress({typing:0,exercises:0,sentences:0,vocab:0})}
function renderMissionBars(){const box=byId('missionBars'); const m=getMission(); byId('missionPreset').value=m.preset; byId('missionLevel').value=m.level; const p=getTodayProgress(); const items=[['Typing passages','typing'],['Exercises','exercises'],['Sentence writing','sentences'],['Vocabulary','vocab']]; box.innerHTML=items.map(([label,key])=>{const cur=p[key]||0,target=m[key]||1,pc=Math.min(100,Math.round(cur*100/target)); return `<div class="card"><div class="row" style="justify-content:space-between"><b>${label}</b><span>${cur}/${target}</span></div><div class="pbar"><span style="width:${pc}%"></span></div></div>`}).join('')}
function setTheme(v){document.body.className=v; localStorage.setItem('theme',v)}
function goHome(){showView('dashboardView')}
function speak(text){if(!text) return; const u=new SpeechSynthesisUtterance(text); u.lang='de-DE'; speechSynthesis.cancel(); speechSynthesis.speak(u); matchLastWord=text}
function showView(id){document.querySelectorAll('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.view===id)); document.querySelectorAll('main > section').forEach(s=>s.classList.toggle('hidden',s.id!==id))}
document.querySelectorAll('.navBtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function populateLevelSelect(id, allowAll=true){const sel=byId(id); sel.innerHTML=''; (allowAll?LEVELS:LEVELS.slice(1)).forEach(v=>{const o=document.createElement('option'); o.value=v; o.textContent=v==='ALL'?'All':v; sel.appendChild(o)})}
function groupPassage(p){return {id:p.id||makeId(), level:(p.level||'').toUpperCase(), chapter:p.chapter||'', title:p.title||((p.german||p.g||'').slice(0,55)), g:p.german||p.g||'', e:p.english||p.e||'', localOnly:!!p.localOnly}}
async function reloadAll(){setStatus('Loading…');
 try{const raw=await loadJson('passages.json'); passages=(Array.isArray(raw)?raw:raw.passages||[]).map(groupPassage).concat(JSON.parse(localStorage.getItem('passages_local')||'[]'));}catch(e){passages=JSON.parse(localStorage.getItem('passages_cache')||'[]')} localStorage.setItem('passages_cache',JSON.stringify(passages));
 try{notesObj=await loadJson('notes.json')}catch(e){notesObj=JSON.parse(localStorage.getItem('notes_cache')||'{}')} localStorage.setItem('notes_cache',JSON.stringify(notesObj));
 try{exercises=(await loadJson('exercises.json')).exercises||[]}catch(e){exercises=JSON.parse(localStorage.getItem('exercises_cache')||'[]')} localStorage.setItem('exercises_cache',JSON.stringify(exercises));
 try{flashcards=(await loadJson('flashcards.json')).flashcards||[]}catch(e){flashcards=JSON.parse(localStorage.getItem('flashcards_cache')||'[]')} localStorage.setItem('flashcards_cache',JSON.stringify(flashcards));
 try{const raw=await loadJson('conjugation.json'); const arr=Array.isArray(raw)?raw:(raw.verbs||[]); conjugations=arr.map(v=>({verb:v.infinitive||v.verb||v.base||'',english:v.english||v.en||'',level:(v.level||'').toUpperCase(),type:v.type||'',forms:v.forms||v.conjugation||v.present||v.prasens||{}})).filter(v=>v.verb)}catch(e){conjugations=JSON.parse(localStorage.getItem('conjugations_cache')||'[]')} localStorage.setItem('conjugations_cache',JSON.stringify(conjugations));
 try{const raw=await loadJson('sentences.json'); if(Array.isArray(raw)) sentences=raw; else if(raw.sentences) sentences=raw.sentences; else {sentences=[]; Object.entries(raw).forEach(([lvl,items])=>Array.isArray(items)&&items.forEach(x=>{if(x&&typeof x==='object'){x.level=x.level||lvl.toUpperCase(); sentences.push(x)}}))}}catch(e){sentences=JSON.parse(localStorage.getItem('sentences_cache')||'[]')} localStorage.setItem('sentences_cache',JSON.stringify(sentences));
 try{vocabItems=(await loadJson('vocab.json')).items||[]}catch(e){vocabItems=JSON.parse(localStorage.getItem('vocab_cache')||'[]')} localStorage.setItem('vocab_cache',JSON.stringify(vocabItems));
 setStatus(`✅ passages:${passages.length} • ✅ notes:${Object.keys(notesObj).length} • ✅ exercises:${exercises.length} • ✅ flashcards:${flashcards.length} • ✅ conjugations:${conjugations.length} • ✅ sentences:${sentences.length} • ✅ vocab:${vocabItems.length}`);
 initAllUI(); }
function initAllUI(){['passageLevelFilter','libLevel','vocabLevel','exLevel','verbLevel','sentLevel'].forEach(id=>populateLevelSelect(id,true)); renderTypingSelect(); renderPassages(); renderVocabTopics(); renderVocab(); renderNotes(); renderExerciseFilters(); resetExerciseFlow(); renderVerbList(); renderSentenceTypes(); resetSentencePractice(); renderFlashcardCategories(); startFlashcards(); renderMissionBars(); renderDashboard(); byId('countPassages').textContent=passages.length; byId('countExercises').textContent=exercises.length; byId('personalNotesArea').value=localStorage.getItem('personal_notes')||''; byId('toolTips').textContent=`• Start from Dashboard, set a daily mission, then move to Practice.
• Use Passages for reading and listening.
• Use Vocabulary match game after each study session.
• Use Grammar tables when cases or pronouns feel unclear.`}
function getPassageFiltered(){const lvl=byId('passageLevelFilter')?.value||'ALL'; return passages.filter(p=>lvl==='ALL'||p.level===lvl)}
function renderTypingSelect(){const sel=byId('practiceSelect'); const arr=getPassageFiltered(); sel.innerHTML=''; arr.forEach((p,i)=>{const o=document.createElement('option'); o.value=i; o.textContent=`${p.level} • ${p.title}`; sel.appendChild(o)}); if(arr.length) sel.value=0; updateReference()}
function updateReference(){const arr=getPassageFiltered(), p=arr[Number(byId('practiceSelect').value)]||arr[0]; byId('referenceArea').value=p?p.g:''; byId('referenceEnglishArea').value=p?p.e:''; byId('referenceEnglishArea').classList.toggle('hidden', byId('showEnglishToggle').value!=='1')}
function onTypingInput(){if(!typingStarted){typingStarted=true; typingStartMs=Date.now()} byId('chars').textContent=byId('practiceArea').value.length}
function clearTyping(){byId('practiceArea').value=''; byId('typingFeedback').textContent=''; byId('diffOutput').classList.add('hidden'); byId('diffOutput').textContent=''; byId('wpm').textContent='0'; byId('acc').textContent='0'; byId('chars').textContent='0'; typingStarted=false}
function diffStrings(ref,typed){let out='',correct=0,max=Math.max(ref.length,typed.length); for(let i=0;i<max;i++){const r=ref[i],t=typed[i]; if(r===undefined&&t!==undefined){out+=`<span class="insChar">${esc(t)}</span>`; continue} if(t===undefined&&r!==undefined){out+=`<span class="missChar">${esc(r)}</span>`; continue} if(r===t){correct++; out+=`<span class="okChar">${esc(t)}</span>`} else out+=`<span class="badChar">${esc(t)}</span>`} return {html:out,accuracy:ref.length?Math.round(correct*100/ref.length):0}}
function checkTyping(){const arr=getPassageFiltered(), p=arr[Number(byId('practiceSelect').value)]||arr[0]; if(!p) return; const typed=byId('practiceArea').value||'', ref=p.g||'', mins=(Date.now()-typingStartMs)/60000||1, wpm=Math.round((typed.trim()?typed.trim().split(/\s+/).length:0)/mins), d=diffStrings(ref,typed); byId('wpm').textContent=wpm; byId('acc').textContent=d.accuracy; if(typed===ref){byId('typingFeedback').innerHTML='<span style="color:var(--good)">✅ Perfect match.</span>'; addTodayProgress({typing:1})} else {byId('typingFeedback').innerHTML='<span style="color:var(--bad)">Not exact.</span> Check punctuation, umlauts, and spacing.'; byId('diffOutput').innerHTML=d.html; byId('diffOutput').classList.remove('hidden'); addTodayProgress({typing:1})}}
function speakSelectedPassage(){const arr=getPassageFiltered(), p=arr[Number(byId('practiceSelect').value)]||arr[0]; if(p) speak(p.g)}
function saveParagraphLocal(){const g=byId('germanInput').value.trim(), e=byId('englishInput').value.trim(), level=byId('localLevel').value; if(!g) return alert('German text required.'); const local=JSON.parse(localStorage.getItem('passages_local')||'[]'); local.push({id:makeId(),g,e,level,title:g.slice(0,60),chapter:'Local passage',localOnly:true}); localStorage.setItem('passages_local',JSON.stringify(local)); byId('germanInput').value=''; byId('englishInput').value=''; reloadAll()}
function renderPassages(){const lvl=byId('libLevel').value||'ALL', q=(byId('libSearch').value||'').toLowerCase(), sort=byId('libSort').value; const list=byId('libraryList'); let arr=passages.filter(p=>(lvl==='ALL'||p.level===lvl)&&(!q||(`${p.title} ${p.chapter} ${p.g} ${p.e}`).toLowerCase().includes(q))); arr=arr.sort((a,b)=> sort==='title' ? a.title.localeCompare(b.title) : (a.level+a.title).localeCompare(b.level+b.title)); list.innerHTML=arr.map(p=>`<div class="card" style="margin-top:10px"><div class="row" style="justify-content:space-between"><div><span class="badge">${esc(p.level)}</span> <b>${esc(p.title)}</b><div class="small" style="margin-top:4px">${esc(p.chapter||'')}</div></div><div class="row"><button class="ghost" onclick='speak(${JSON.stringify(p.g)})'>🔊 Listen</button>${p.localOnly?`<button class="danger" onclick="deleteLocalPassage('${p.id}')">Delete</button>`:''}</div></div><div class="passageBody" style="margin-top:10px">${esc(p.g)}</div>${p.e?`<div class="small passageBody" style="margin-top:8px">EN: ${esc(p.e)}</div>`:''}</div>`).join('')||'<div class="small">No passages found.</div>'}
function deleteLocalPassage(id){const local=JSON.parse(localStorage.getItem('passages_local')||'[]').filter(x=>x.id!==id); localStorage.setItem('passages_local',JSON.stringify(local)); reloadAll()}
function renderVocabTopics(){const sel=byId('vocabTopic'); const cur=sel.value||'ALL'; const topics=[...new Set(vocabItems.map(v=>v.topic).filter(Boolean))].sort(); sel.innerHTML='<option value="ALL">All topics</option>'+topics.map(t=>`<option>${esc(t)}</option>`).join(''); if(topics.includes(cur)) sel.value=cur}
function renderVocab(){const lvl=byId('vocabLevel').value||'ALL', topic=byId('vocabTopic').value||'ALL', q=(byId('vocabSearch').value||'').toLowerCase(); const arr=vocabItems.filter(v=>(lvl==='ALL'||v.level===lvl)&&(topic==='ALL'||v.topic===topic)&&(!q||(`${v.de} ${v.en} ${v.topic}`).toLowerCase().includes(q))); byId('vocabCount').textContent=`${arr.length} vocabulary items shown`; byId('vocabList').innerHTML=arr.slice(0,250).map(v=>`<div class="card" style="margin-top:10px"><div class="row" style="justify-content:space-between"><div><span class="badge">${esc(v.level)}</span> <b>${esc(v.de)}</b> — ${esc(v.en)}</div><button class="ghost" onclick='speak(${JSON.stringify(v.de)})'>🔊</button></div><div class="small" style="margin-top:6px">${esc(v.topic||'')}</div>${v.example_de?`<div style="margin-top:8px">${esc(v.example_de)}</div>`:''}${v.example_en?`<div class="small" style="margin-top:4px">EN: ${esc(v.example_en)}</div>`:''}<div class="row" style="margin-top:8px"><button class="ghost" onclick="markVocabReviewed()">Mark reviewed</button></div></div>`).join('')||'<div class="small">No vocabulary found for this filter.</div>'}
function markVocabReviewed(){addTodayProgress({vocab:1})}
function newMatchGame(){const lvl=byId('vocabLevel').value||'ALL'; const arr=vocabItems.filter(v=>lvl==='ALL'||v.level===lvl); const picked=shuffle(arr).slice(0,5); matchPool=[]; picked.forEach((v,i)=>{matchPool.push({id:'g'+i,pair:i,text:v.de,lang:'de'},{id:'e'+i,pair:i,text:v.en,lang:'en'})}); matchPool=shuffle(matchPool); matchSelected=[]; matchSolved=0; renderMatchGrid(); byId('matchInfo').textContent='Match each German word with the English meaning.'}
function renderMatchGrid(){byId('matchGrid').innerHTML=matchPool.map(c=>`<div class="matchCard ${c.done?'done':''} ${matchSelected.includes(c.id)?'sel':''}" onclick="selectMatch('${c.id}')">${c.done?'✓ '+esc(c.text):esc(c.text)}</div>`).join('')}
function selectMatch(id){const card=matchPool.find(x=>x.id===id); if(!card||card.done) return; if(matchSelected.includes(id)){matchSelected=matchSelected.filter(x=>x!==id); renderMatchGrid(); return;} matchSelected.push(id); renderMatchGrid(); if(matchSelected.length===2){const [a,b]=matchSelected.map(id=>matchPool.find(x=>x.id===id)); if(a.pair===b.pair&&a.lang!==b.lang){a.done=b.done=true; matchSelected=[]; matchSolved++; byId('matchInfo').textContent='✅ Correct match!'; addTodayProgress({vocab:1}); if(matchSolved===5) byId('matchInfo').textContent='🎉 Great. All pairs matched.'; renderMatchGrid()} else {byId('matchInfo').textContent='Not a match. Try again.'; setTimeout(()=>{matchSelected=[]; renderMatchGrid()},650)}}}
function speakMatchWord(){if(matchSelected.length){const c=matchPool.find(x=>x.id===matchSelected[0]); if(c&&c.lang==='de') speak(c.text)}}
async function lookupWord(){const q=byId('dictWord').value.trim(); if(!q) return; const local=vocabItems.filter(v=>normAnswer(v.de)===normAnswer(q)||normAnswer(v.en)===normAnswer(q)); if(local.length){byId('dictResult').textContent='From your app vocabulary\n\n'+local.slice(0,8).map(v=>`${v.de} — ${v.en}${v.topic?` (${v.topic})`:''}`).join('\n'); return} byId('dictResult').textContent='Not found in app vocabulary yet. Try searching in the word list or add it to notes.'}
function renderNotes(){const sel=byId('notesTopic'); const keys=Object.keys(notesObj); sel.innerHTML=keys.map(k=>`<option>${esc(k)}</option>`).join(''); sel.onchange=()=>byId('notesArea').value=String(notesObj[sel.value]||''); if(keys.length){sel.value=keys[0]; byId('notesArea').value=String(notesObj[keys[0]]||'')} }
function savePersonalQuickNote(){const v=byId('personalNotesInput').value.trim(); if(!v) return; const existing=localStorage.getItem('personal_notes')||''; const next=existing ? existing+'\n• '+v : '• '+v; localStorage.setItem('personal_notes',next); byId('personalNotesArea').value=next; byId('personalNotesInput').value=''; byId('personalNotesStatus').textContent='Saved locally.'}
function clearPersonalNotes(){localStorage.removeItem('personal_notes'); byId('personalNotesArea').value=''; byId('personalNotesStatus').textContent='Cleared.'}
function renderExerciseFilters(){populateLevelSelect('exLevel',true); const groups=[...new Set(exercises.map(e=>e.group||'general'))].sort(); byId('exGroup').innerHTML='<option value="ALL">All useful types</option>'+groups.map(g=>`<option value="${g}">${g.replaceAll('_',' ')}</option>`).join('')}
function buildExercisePool(){const lvl=byId('exLevel').value||'ALL', group=byId('exGroup').value||'ALL', order=byId('exOrder').value; exPool=exercises.filter(e=>(lvl==='ALL'||(e.level||'').toUpperCase()===lvl)&&(group==='ALL'||(e.group||'general')===group)); exPool=order==='random'?shuffle(exPool):exPool.slice().sort((a,b)=>(a.id||0)-(b.id||0)); exIndex=0}
function resetExerciseFlow(){buildExercisePool(); byId('exFeedback').textContent=''; nextExercise(true)}
function renderExercise(e){byId('exMCQ').innerHTML=''; byId('exTypingWrap').classList.add('hidden'); byId('exTyping').value=''; if(!e){byId('exQ').textContent='No exercises found for this filter.'; byId('exHint').textContent='Change the level or practice type.'; byId('exProg').textContent='0/0'; byId('exMeta').textContent='Mode: -'; return} byId('exQ').textContent=e.question; byId('exHint').textContent=`${e.level} • ${String(e.group||'general').replaceAll('_',' ')} • ${e.type}`; byId('exProg').textContent=`${Math.min(exIndex+1,exPool.length)}/${exPool.length}`; byId('exMeta').textContent=`Mode: ${e.mode||'typing'}`; if(e.mode==='mcq'&&Array.isArray(e.options)){e.options.forEach(opt=>{const b=document.createElement('button'); b.textContent=opt; b.className='ghost'; b.onclick=()=>checkExerciseMCQ(opt); byId('exMCQ').appendChild(b)})} else {byId('exTypingWrap').classList.remove('hidden')}}
function nextExercise(first=false){if(!exPool.length){renderExercise(null); return} if(!first){exIndex=(exIndex+1)%exPool.length} exCurrent=exPool[exIndex]; byId('exFeedback').textContent=''; renderExercise(exCurrent)}
function checkExerciseMCQ(choice){if(!exCurrent) return; const ok=normAnswer(choice)===normAnswer(exCurrent.answer); byId('exFeedback').innerHTML=ok?'<span style="color:var(--good)">✅ Correct</span>':`<span style="color:var(--bad)">❌</span> Correct: <b>${esc(exCurrent.answer)}</b>`; addTodayProgress({exercises:1})}
function checkExerciseTyping(){if(!exCurrent) return; const inp=byId('exTyping').value; const ok=normAnswer(inp)===normAnswer(exCurrent.answer); byId('exFeedback').innerHTML=ok?'<span style="color:var(--good)">✅ Correct</span>':`<span style="color:var(--bad)">❌</span> Correct: <b>${esc(exCurrent.answer)}</b>`; addTodayProgress({exercises:1})}
function renderVerbList(){const q=(byId('verbSearch').value||'').toLowerCase(), lvl=byId('verbLevel').value||'ALL'; const sel=byId('verbSelect'); sel.innerHTML=''; const arr=conjugations.filter(v=>(lvl==='ALL'||v.level===lvl)&&(!q||(`${v.verb} ${v.english}`).toLowerCase().includes(q))).sort((a,b)=>a.verb.localeCompare(b.verb)); arr.forEach(v=>{const o=document.createElement('option'); o.value=v.verb; o.textContent=`${v.verb} — ${v.english||''}`; sel.appendChild(o)}); if(arr.length) sel.value=arr[0].verb; renderVerb()}
function renderVerb(){const chosen=byId('verbSelect').value; const v=conjugations.find(x=>x.verb===chosen); if(!v){byId('verbTitle').textContent='No verb'; return} byId('verbTitle').textContent=v.verb; byId('verbMeta').textContent=`${v.english||''} • ${v.level||''} • ${v.type||''}`; ['ich','du','er','wir','ihr','sie'].forEach(k=>{byId('v_'+k).textContent=(v.forms||{})[k]||'—'})}
function startVerbQuiz(){const chosen=byId('verbSelect').value; const v=conjugations.find(x=>x.verb===chosen); if(!v) return; const pron=['ich','du','er','wir','ihr','sie'][Math.floor(Math.random()*6)]; verbQuiz={verb:v,pron,answer:(v.forms||{})[pron]||''}; byId('verbQuizQ').textContent=`Conjugate ${v.verb} for ${pron}:`; byId('verbQuizInput').value=''; byId('verbQuizFeedback').textContent=''}
function checkVerbQuiz(){if(!verbQuiz) return; const ok=normAnswer(byId('verbQuizInput').value)===normAnswer(verbQuiz.answer); byId('verbQuizFeedback').innerHTML=ok?'<span style="color:var(--good)">✅ Correct</span>':`<span style="color:var(--bad)">❌</span> Correct: <b>${esc(verbQuiz.answer)}</b>`; addTodayProgress({exercises:1})}
function guessSentenceType(de){const s=(de||'').toLowerCase(); if(/\?$/.test(de||'')) return 'questions'; if(/weil|dass|wenn|obwohl|damit/.test(s)) return 'subordinate clauses'; if(/mich|dich|sich|uns|euch/.test(s)) return 'reflexive'; if(/werde|wirst|wird|werden/.test(s)) return 'future/passive'; return 'core sentences'}
function renderSentenceTypes(){populateLevelSelect('sentLevel',true); const types=[...new Set(sentences.map(s=>s.type||guessSentenceType(s.de||s.german||'')))].sort(); byId('sentType').innerHTML='<option value="ALL">All sentence types</option>'+types.map(t=>`<option>${esc(t)}</option>`).join('')}
function buildSentencePool(){const lvl=byId('sentLevel').value||'ALL', type=byId('sentType').value||'ALL', order=byId('sentOrder').value; sentPool=sentences.map((s,i)=>({id:i+1,level:(s.level||'').toUpperCase(),prompt:s.en||s.english||s.title||'Write the German sentence',sample:s.de||s.german||'',type:s.type||guessSentenceType(s.de||s.german||''),hint:s.hint||''})).filter(s=>(lvl==='ALL'||s.level===lvl)&&(type==='ALL'||s.type===type)); sentPool=order==='random'?shuffle(sentPool):sentPool; sentIndex=0}
function resetSentencePractice(){buildSentencePool(); nextSentence(true)}
function nextSentence(first=false){if(!sentPool.length){byId('sentPrompt').textContent='No sentence task found.'; return} if(!first) sentIndex=(sentIndex+1)%sentPool.length; sentCurrent=sentPool[sentIndex]; byId('sentPrompt').textContent=sentCurrent.prompt; byId('sentMeta').textContent=`${sentCurrent.level} • ${sentCurrent.type}`; byId('sentAnswer').value=''; byId('sentFeedback').textContent=''; byId('sentSamples').textContent=''}
function checkSentence(){if(!sentCurrent) return; const ok=normAnswer(byId('sentAnswer').value)===normAnswer(sentCurrent.sample); byId('sentFeedback').innerHTML=ok?'<span style="color:var(--good)">✅ Sample match.</span>':`Not an exact sample match. Sample: <b>${esc(sentCurrent.sample)}</b>`; addTodayProgress({sentences:1})}
function showSentenceSample(){if(sentCurrent) byId('sentSamples').textContent='Sample: '+sentCurrent.sample}
function renderFlashcardCategories(){const cats=[...new Set(flashcards.map(f=>f.category).filter(Boolean))].sort(); byId('fcCategory').innerHTML='<option value="ALL">All</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('')}
function startFlashcards(){const cat=byId('fcCategory').value||'ALL', q=(byId('fcSearch').value||'').toLowerCase(); fcPool=flashcards.filter(f=>(cat==='ALL'||f.category===cat)&&(!q||(`${f.front} ${f.back}`).toLowerCase().includes(q))); fcPool=shuffle(fcPool); fcIndex=0; fcFlipped=false; renderFlash()}
function renderFlash(){const f=fcPool[fcIndex]; byId('flashCard').innerHTML=f?esc(fcFlipped?f.back:f.front):'No flashcards'; byId('flashMeta').textContent=f?`${fcIndex+1}/${fcPool.length} • ${f.category||''} • tap to flip`:''}
function flipFlash(){fcFlipped=!fcFlipped; renderFlash()} function nextFlash(){if(!fcPool.length) return; fcIndex=(fcIndex+1)%fcPool.length; fcFlipped=false; renderFlash()} function prevFlash(){if(!fcPool.length) return; fcIndex=(fcIndex-1+fcPool.length)%fcPool.length; fcFlipped=false; renderFlash()}
function renderDashboard(){const p=getTodayProgress(), m=getMission(); const done=(p.typing+p.exercises+p.sentences+p.vocab), target=(m.typing+m.exercises+m.sentences+m.vocab); let emoji='🌱'; if(done>=target) emoji='🏆'; else if(done>target*0.66) emoji='🔥'; else if(done>target*0.33) emoji='🚀'; byId('todayEmoji').textContent=emoji; byId('todaySummary').textContent=`${done}/${target} tasks done today for ${m.level} mission.`; byId('learningPathBox').innerHTML=`<b>A1</b> build articles, question words, present tense, short daily passages.<br><br><b>A2</b> add Perfekt, modal verbs, weil/dass/wenn, reflexive verbs, short emails.<br><br><b>B1</b> focus on work, neighbours, health, environment, culture, connectors, relative clauses, passive basics.<br><br><b>B2</b> move to Konjunktiv II, passive alternatives, opinion writing, abstract vocabulary, longer arguments.`; byId('todayPlan').innerHTML=`• ${m.typing} passage typing checks<br>• ${m.exercises} exercises from grouped practice types<br>• ${m.sentences} sentence-writing prompts<br>• ${m.vocab} vocabulary reviews or match pairs<br><br>Best next step: start in Practice, then use Vocabulary match game, and finally revise Notes.`}
async function translateText(){const txt=byId('translateInput').value.trim(); if(!txt) return; const sl=byId('langFrom').value, tl=byId('langTo').value; try{const res=await fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl='+sl+'&tl='+tl+'&dt=t&q='+encodeURIComponent(txt)); const data=await res.json(); byId('translateOutput').value=(data[0]||[]).map(x=>x[0]).join('')}catch(e){byId('translateOutput').value='Translation failed.'}}
function swapLangs(){const a=byId('langFrom'), b=byId('langTo'); const t=a.value; a.value=b.value; b.value=t}
document.querySelectorAll('[data-psub]').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('[data-psub]').forEach(x=>x.classList.remove('active')); b.classList.add('active'); ['typingPane','exercisePane','conjPane','sentencePane'].forEach(id=>byId(id).classList.toggle('hidden',id!==b.dataset.psub))});
document.querySelectorAll('[data-vsub]').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('[data-vsub]').forEach(x=>x.classList.remove('active')); b.classList.add('active'); ['vocabListPane','vocabGamePane','dictPane'].forEach(id=>byId(id).classList.toggle('hidden',id!==b.dataset.vsub)); if(b.dataset.vsub==='vocabGamePane' && !matchPool.length) newMatchGame()});
document.querySelectorAll('[data-nsub]').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('[data-nsub]').forEach(x=>x.classList.remove('active')); b.classList.add('active'); ['notesPane','grammarPane'].forEach(id=>byId(id).classList.toggle('hidden',id!==b.dataset.nsub))});
(function init(){const theme=localStorage.getItem('theme')||'theme-focus'; setTheme(theme); byId('themeSelect').value=theme; applyMissionPreset(); reloadAll();})();
